"""Turning `claude --output-format stream-json` events into a live text log.

Each run gets one append-only text file under `data/runs/<run_id>.log`. The web
UI tails it by byte offset (see `/api/run/{id}/log`), which is why the writer
only ever appends and never rewrites: an offset handed out earlier stays valid.
"""
from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any, Optional

from app import apiretry, config

# The field of a tool's input that best identifies what it is doing. Anything
# not listed falls back to the first short string value in the input dict.
TOOL_SUMMARY_KEYS: dict[str, str] = {
    "Bash": "command",
    "Read": "file_path",
    "Write": "file_path",
    "Edit": "file_path",
    "NotebookEdit": "notebook_path",
    "Glob": "pattern",
    "Grep": "pattern",
    "Task": "description",
    "Agent": "description",
    "WebFetch": "url",
    "WebSearch": "query",
    "Skill": "skill",
}

MAX_SUMMARY_CHARS = 160

# The first character of a log line says what kind of line it is, and the web
# console reads it to decide how to draw the line. Wes, 2026-07-28: "make all
# the tool calls and '>' lines show as indented gray/dimmed text with the other
# lines where the agent is just talking or thinking show as non-indented text
# that is not dimmed."
#
# So the *machinery* of a run - what it called, what came back - is the quiet
# background, and what the agent actually said is the foreground. That is the
# opposite of how this file used to write it: prose carried a two-space indent
# and tool calls sat at column 0.
#
# Prose therefore has NO marker. It is the unmarked case on purpose: it is what
# a person is reading the transcript for, it is the only kind whose text is not
# generated by this file, and leaving it bare means `cat`ing the raw log shows
# the same shape the browser does.
TOOL = ">"
RESULT = "<"
ERROR = "!"
STATUS = "*"
THINK = "~"

# marker -> the name the stylesheet and app.js know it by. Published because
# app/static/app.js carries the same table (it has to classify lines it
# appends live, and cannot call into Python to do it); tests/test_console.py
# pins the two together so a marker added here cannot be missed there.
MARKERS: dict[str, str] = {
    TOOL: "tool",
    RESULT: "result",
    ERROR: "error",
    STATUS: "status",
    THINK: "think",
}


def escape_prose(line: str) -> str:
    """A line of the agent's own words, made safe to store unmarked.

    Agent prose is markdown, and markdown is full of `> quoted` and `* bullet`
    lines. Left alone, those would be read back as a tool call and a status
    line and drawn as dimmed machinery - the agent's own emphasis turned into
    something it never said.

    One leading space is enough, because the reader only treats a marker as a
    marker at position 0. Indentation inside prose is content (a fenced code
    block means its indentation), so nothing is stripped on the way out and a
    line that needs no escape is returned untouched.
    """
    if line[:1] in MARKERS:
        return " " + line
    return line


def _clip(text: str, limit: int = MAX_SUMMARY_CHARS) -> str:
    text = " ".join(str(text).split())
    if len(text) <= limit:
        return text
    return text[: limit - 1] + "…"


def summarize_tool_input(name: str, tool_input: Any) -> str:
    if not isinstance(tool_input, dict):
        return _clip(tool_input or "")
    key = TOOL_SUMMARY_KEYS.get(name)
    if key and tool_input.get(key):
        return _clip(tool_input[key])
    for value in tool_input.values():
        if isinstance(value, str) and value.strip():
            return _clip(value)
    return ""


def _content_blocks(event: dict) -> list[dict]:
    message = event.get("message")
    if not isinstance(message, dict):
        return []
    content = message.get("content")
    if isinstance(content, str):
        return [{"type": "text", "text": content}]
    if not isinstance(content, list):
        return []
    return [b for b in content if isinstance(b, dict)]


def _result_text(block: dict) -> str:
    content = block.get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(
            part.get("text", "") for part in content if isinstance(part, dict)
        )
    return ""


MAX_SAID_CHARS = 200

# Lines that are markdown furniture rather than words: a heading's hashes, a
# bullet's dash or star, a quote's chevron. Stripped so a report that opens
# "## What I did" reads as "What I did" on a strip that renders no markdown.
_MD_LEAD = re.compile(r"^(?:#{1,6}\s+|[-*+]\s+|\d+[.)]\s+|>\s*)+")


def said(event: dict) -> str:
    """What the agent SAID in this event, as one line - or "" if it said
    nothing (a tool-only turn, a tool result, a status event).

    The dashboard strip, the rail and the Telegram status used to show only
    the newest rendered log line, which for almost every assistant turn is
    the tool call it ended on: "> Bash(cd /srv/portal/... <<'EOF' import
    sqlite3". Wes reads that strip on his phone to know what an agent is up
    to, and a truncated shell command does not say. The agent's own words do -
    every run narrates ("Checking whether the run page already shows holds")
    because its harness asks it to - so this picks the prose out of the event
    for the surfaces that show one line. Thinking blocks are not words to a
    reader (and are off on this install); tool calls are the other line.
    """
    if event.get("type") != "assistant":
        return ""
    texts = []
    for block in _content_blocks(event):
        if block.get("type") == "text":
            text = (block.get("text") or "").strip()
            if text:
                texts.append(text)
    if not texts:
        return ""
    words = []
    for line in "\n".join(texts).splitlines():
        line = _MD_LEAD.sub("", line.strip())
        if line:
            words.append(line)
    flat = re.sub(r"\s+", " ", " ".join(words)).strip()
    if len(flat) <= MAX_SAID_CHARS:
        return flat
    cut = flat[:MAX_SAID_CHARS]
    # Back up to the last word boundary, unless the text is one huge token.
    if " " in cut[MAX_SAID_CHARS // 2:]:
        cut = cut[: cut.rfind(" ")]
    return cut.rstrip(" ,;:-") + "\u2026"


def render_event(event: dict) -> list[str]:
    """One stream-json event -> zero or more display lines.

    Returns a list (not a string) because a single assistant turn can carry
    both prose and several tool calls, and each deserves its own line.
    """
    etype = event.get("type")

    if etype == "system" and event.get("subtype") == "init":
        model = event.get("model") or "?"
        tools = event.get("tools") or []
        return [f"{STATUS} session start  model={model}  tools={len(tools)}"]

    if etype == "system" and event.get("subtype") == "api_retry":
        # The only output a run produces while the CLI is waiting out a failed
        # API call. Dropped, as it was before, the console shows a run that has
        # simply stopped moving for ten minutes with nothing to say why.
        #
        # STATUS rather than ERROR, and that is not cosmetic: the console folds
        # tool calls and errors away behind "show tool calls", so an ERROR line
        # would have made a run stalled for three minutes read as "3 errors" in
        # a collapsed summary - quiet again, which is the whole thing this is
        # meant to fix. It is also honest. The CLI is handling the failure and
        # most retries succeed; what a reader needs to see is that the run is
        # waiting and why, alongside "session start" and "run complete".
        retry = apiretry.classify(event)
        if retry is None:
            return []
        return [f"{STATUS} API {retry.describe()}"]

    if etype == "assistant":
        lines: list[str] = []
        for block in _content_blocks(event):
            btype = block.get("type")
            if btype == "text":
                text = (block.get("text") or "").strip()
                if text:
                    # Unmarked and unindented: this is the thing being read.
                    lines.extend(escape_prose(ln) for ln in text.splitlines())
            elif btype == "thinking":
                # Wes asked for thinking to read like talking. It was being
                # dropped on the floor entirely before this - a transcript that
                # showed the tool calls but not the reasoning between them.
                text = (block.get("thinking") or "").strip()
                lines.extend(f"{THINK} {ln}" for ln in text.splitlines() if ln.strip())
            elif btype == "tool_use":
                name = block.get("name") or "tool"
                lines.append(
                    f"{TOOL} {name}({summarize_tool_input(name, block.get('input'))})"
                )
        return lines

    if etype == "user":
        lines = []
        for block in _content_blocks(event):
            if block.get("type") != "tool_result":
                continue
            text = _result_text(block)
            count = len([ln for ln in text.splitlines() if ln.strip()])
            if block.get("is_error"):
                lines.append(f"{ERROR} error: {_clip(text)}")
            else:
                lines.append(
                    f"{RESULT} ok ({count} line{'' if count == 1 else 's'})"
                )
        return lines

    if etype == "result":
        turns = event.get("num_turns")
        cost = event.get("total_cost_usd")
        bits = []
        if turns is not None:
            bits.append(f"{turns} turns")
        if cost is not None:
            # Log lines are frozen at write time, so they can't follow the
            # display-units setting the way the templates do. They use the
            # unit-neutral weight suffix rather than claiming a dollar amount.
            bits.append(f"{cost:.3f}w")
        detail = f"  ({', '.join(bits)})" if bits else ""
        if event.get("is_error"):
            # The subtype is frequently the only "why" the CLI gives - on a
            # max-turns kill the result string is empty - so the log line
            # carries it rather than reporting an anonymous failure.
            subtype = event.get("subtype")
            why = ""
            if subtype == "error_max_turns":
                why = " - hit the turn limit"
            elif subtype and subtype != "success":
                why = f" - {subtype}"
            return [f"{ERROR} run failed{why}{detail}"]
        return [f"{STATUS} run complete{detail}"]

    return []


def log_path(run_id: int) -> Path:
    return config.RUNS_DIR / f"{run_id}.log"


KEEP_LOGS = 200


def prune(keep: int = KEEP_LOGS) -> int:
    """Drop all but the `keep` newest transcripts. Called when a run starts, so
    a long-lived portal doesn't accumulate log files forever. Returns how many
    were removed."""
    if not config.RUNS_DIR.exists():
        return 0
    logs = sorted(config.RUNS_DIR.glob("*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
    removed = 0
    for stale in logs[keep:]:
        try:
            stale.unlink()
            removed += 1
        except OSError:
            pass
    return removed


class RunLog:
    """Append-only writer for one run's live log."""

    def __init__(self, run_id: int) -> None:
        self.run_id = run_id
        self.path = log_path(run_id)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        prune()
        # A re-used run id (only possible if the DB was reset) must not show
        # the previous run's transcript.
        self.path.write_text("", encoding="utf-8")

    def append(self, lines: list[str]) -> None:
        if not lines:
            return
        with open(self.path, "a", encoding="utf-8") as f:
            f.write("".join(f"{line}\n" for line in lines))


def read_log(run_id: int, offset: int = 0) -> tuple[str, int]:
    """Bytes from `offset` on, plus the new offset. Missing file -> ("", 0)."""
    path = log_path(run_id)
    if not path.exists():
        return "", 0
    size = path.stat().st_size
    if offset > size:  # log was truncated/restarted under us
        offset = 0
    with open(path, "rb") as f:
        f.seek(offset)
        chunk = f.read()
    return chunk.decode("utf-8", errors="replace"), offset + len(chunk)


def is_complete(text: str) -> bool:
    """Whether a log reached its closing line.

    The last thing a watched run writes is the CLI's `result` event, rendered
    as "run complete" or "run failed" above. A log that ends on anything else
    stopped being written before the run stopped: the portal restarted under
    the run and the rest of its stdout went down a dead pipe, or the run was
    killed. Either way the file is not the whole story, and the run page
    (main._render_run_page) goes looking for the CLI's own transcript instead.
    """
    for line in reversed(text.splitlines()):
        if not line.strip():
            continue
        return line.startswith(f"{STATUS} run complete") or line.startswith(f"{ERROR} run failed")
    return False


def tail(run_id: int, max_lines: int = 40) -> str:
    text, _ = read_log(run_id, 0)
    lines = text.splitlines()
    return "\n".join(lines[-max_lines:])


def parse_line(raw: str) -> Optional[dict]:
    raw = raw.strip()
    if not raw:
        return None
    try:
        event = json.loads(raw)
    except json.JSONDecodeError:
        return None
    return event if isinstance(event, dict) else None
